before_install:
  - travis_retry sudo apt-add-repository ppa:bpaquet/zeromq4-precise -y
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install libzmq-dev -y
language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - ruby-head
cache:
  - bundler
  - apt

matrix:
  allow_failures:
    - rvm: ruby-head
